name: Cypress Tests using Cypress Docker Image

on:
  pull_request:
    types: [opened, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    container: cypress/browsers:node16.14.0-slim-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - name: install pip
        run: |  
          cat /etc/*-release
          python3 --version
          # python3 -m ensurepip --default-pip
          #python3 -m pip install --upgrade pip setuptools wheel        
          apt update -qq
          apt install -y python3-pip
          # python --version
          pip3 --version
          # pip --version

      # - name: setup django
      #   run: pip install django

      - name: Checkout xblock-sdk repo
        uses: actions/checkout@v3
        with:
          repository: openedx/xblock-sdk
          path: xblock-sdk

      - name: Setup xblock-sdk
        working-directory: xblock-sdk
        run: |
          pwd
          pip install -r requirements/dev.txt
          pip install -r requirements/local.txt
          python3 ./manage.py runserver

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          browser: chrome
          record: true